

## infile: output file generated by decipherMutationalProcesses
## outfile: output pdf file name

plot_stability_and_reconstruction_error <-
  function(infile = "parameter_index.txt")
  {
    
  d <- read.table(infile, header = TRUE)
  twoord.plot(
    d$Rank,
    d$Stability,
    d$Rank,
    d$ReconstructionError,
    las = 1,
    rylab = "Reconstruction error",
    ylab = "Stability",
    xlab = "NMF rank"
  )
  
  }

run_example <- function()
{
  library(plotrix)
  setwd("/Users/lixiangchun/Public/WorkSpace/Project/DigestiveSystemCancer/LiverCancer/decipherMutationalProcesses/mult/output")
  pdf("parameter_index.pdf", width=6, height = 4)
  plot_stability_and_reconstruction_error("parameter_index.txt")
  dev.off()
}
